# Generated by Django 3.2.4 on 2021-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210701_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='briefly',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
