# Generated by Django 3.2.4 on 2021-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
